### PR TITLE
if remote is true, use default remote from config

### PR DESCRIPTION
**Pull request by zouter**

### CODE REVIEW

**Comment by zouter** [comment]
image

**Comment by rcannood** [comment]
Hmm. If we're changing things, I'd rather have it behave somewhat similarly to `qsub_lapply`.

Perhaps for all non-qsub_lapply functions:

* If `remote` is `FALSE`, use do it local
* If `remote` is `TRUE` or `NULL`, use `get_default_qsub_config()$remote`
* Otherwise assume `remote` is a character and just use that.

I'll refactor it tomorrow :gift: :wink:

**Comment by zouter** [comment]
Okidoki :bowing_man: :bowing_woman:

**Comment by rcannood** [comment]
Happy birthday! 
:tada: :confetti_ball: :gift: :birthday:

**Comment by zouter** [comment]
Merging this pull request is the perfect present :heart_eyes:

**Pull request merged**
